spring:
  datasource:
    url: jdbc:sqlserver://webdoldatbase.database.windows.net:1433;database=webdatabase;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: webdoldatbase_root
    password: Password@12
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080